feat(pagination): adding text-decoration, and font-weight for accessibility
Availity/availity-uikit pull request #283
Opened 2021-08-04 22:54 UTC by clintonlunn

This PR aims to better distinguish between active and inactive buttons for pagination components. Adding in bold font-weight for the active button and underlining the inactive buttons to help for accessibility. 

![2021-08-04_18-43-25 (1)](https://user-images.githubusercontent.com/24685932/128265117-32697aa8-40c2-4714-9759-a019b87f8b24.gif)

2021-08-05 15:21 UTC, LauRoxx requested changes

2021-08-05 15:28 UTC, jordan-a-young commented
I think we should reverse how the hover works. Have the inactive buttons not underlined, and then add the underline on hover.

2021-08-05 16:11 UTC, clintonlunn commented
Made the changes that @LauRoxx requested. 

![2021-08-05_12-09-37 (1)](https://user-images.githubusercontent.com/24685932/128383948-cfe5d64a-5ad5-4505-8465-10bdd0fed949.gif)

2021-08-06 15:31 UTC, clintonlunn commented
![2021-08-06_11-24-42 (1)](https://user-images.githubusercontent.com/24685932/128535020-aa5dda2a-95c7-47d5-a74c-56e65a1395c8.gif)
example of unstyled pagination.

2021-08-09 18:38 UTC, LauRoxx commented on packages/uikit/scss/_pagination.scss
>      }
I don't think we want a different behavior for focus and hover. If we're not doing background color for the unstyled hover we should probably also lose it for focus and make the behaviors match. focus will have a border anyway.

@jordan-a-young thoughts?

2021-08-10 18:13 UTC, LauRoxx commented on packages/uikit/scss/_pagination.scss
>      }
Awesome. I believe the focus outline is already inherited, so just get rid of the bg color and make hover & focus color=black.

2021-08-10 19:29 UTC, clintonlunn commented
@LauRoxx I believe I've addressed your changes.

2021-08-10 20:35 UTC, LauRoxx approved these changes

2021-08-10 20:55 UTC, clintonlunn commented
current look of unstyled pagination: 
![2021-08-10_14-38-21 (1)](https://user-images.githubusercontent.com/24685932/128933784-aaccea4a-c47e-47ca-ab4c-e2999d84817c.gif)

2021-08-10 21:03 UTC, merged